import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from fpdf import FPDF
from datetime import datetime
import os

def generate_pdf_report(counts, image_name, output_dir="reports"):
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf_path = os.path.join(output_dir, f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Blood Cell Analysis Report", ln=True, align="C")

    pdf.set_font("Arial", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, f"Image: {image_name}", ln=True)
    pdf.cell(0, 10, f"Date: {timestamp}", ln=True)
    pdf.ln(10)

    total_cells = sum(counts.values())
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Detected Cell Counts:", ln=True)

    pdf.set_font("Arial", "", 12)
    for cell_type, count in counts.items():
        pdf.cell(0, 10, f"{cell_type}: {count}", ln=True)

    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Total Cells Detected: {total_cells}", ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by Blood Cell Identifier App", ln=True, align="C")

    pdf.output(pdf_path)
    return pdf_path